{{- if eq .Values.are.enabled true }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: anps-allow-access-from-ingress
  labels:
    component: are
spec:
  selector:
    matchLabels:
      app: are-notification-processing-service
  action: ALLOW
  rules:
    - from:
      - source:
          principals: 
            - "cluster.local/ns/istio-system/sa/istio-ingressgateway"
            {{- include "policies-authorization-chart.gateway_service_accounts" (dict "namespace" .Release.Namespace "services" .Values.are.gateway.services) | indent 12}}
      to:
      - operation:
          methods: ["POST"]
          {{- if eq .Values.featureFlags.newApiEndpoints true }}
          paths: [
            "/$are-process-notification",
            "/%24are-process-notification"
          ]
          {{- else }}
          paths: [
            "/fhir/$are-process-notification",
            "/fhir/%24are-process-notification"
          ]
          {{- end }}
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ 
            "are-notification-sender",
           ]
    {{/* Allow all operations for the given IPs */}}
    {{- (include "policies-authorization-chart.allow_all_operations_for_ips" .) | indent 4 }}
{{- end }}