{{- if and (eq .Values.dmz.enabled true) (eq .Values.dmz.featureFlags.arsBulkEnabled true) }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: bulk-inbound-service-allow-access-from-ingress
  labels:
    component: bulk-inbound-service
spec:
  selector:
    matchLabels:
      app: bulk-inbound-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
          "cluster.local/ns/istio-system/sa/istio-ingressgateway",
        ]
    to:
    - operation:
        methods: [ "POST" ]

        paths: [
          "/batch/fhir/bundle",
          "/batch/upload",
          "/batch/upload*"
        ]
    when:
      - key: request.auth.claims[realm_access][roles]
        values: [ "ars-data-sender" ]
{{- end }}

