{{- if and (eq .Values.dmz.enabled true) (eq .Values.pgbouncer.enabled true) (eq .Values.tcp.principals.enabled true)}}
{{/* Allows the Cluster Services to access PgBouncer */}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: pgbouncer-allow-access-from-internal
  labels:
    component: database
spec:
  selector:
    matchLabels:
      app: pgbouncer
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
            "cluster.local/ns/{{ .Release.Namespace }}/sa/bulk-inbound-service*"
          ]
    to:
    - operation:
        # TCP Only
        ports: ["5432"]
{{- end }}
