{{- if (eq .Values.dmz.rabbitmq.enabled true) }}
{{/* Allows the Cluster Services to access RabbitMq */}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: rabbit-mq-allow-access-from-secure-message-gateway
  labels:
    component: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
          "cluster.local/ns/{{ .Release.Namespace }}/sa/secure-message-gateway*"
        ]
    to:
    - operation:
        ports: ["5672"]
{{- end }}
