{{- if (eq .Values.dmz.rabbitmq.enabled true) }}
{{/* Allows the Cluster Services to access RabbitMq */}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: secure-message-gateway-allow-access-from-waf
  labels:
    component: secure-message-gateway
spec:
  selector:
    matchLabels:
      app: secure-message-gateway
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
          "cluster.local/ns/{{ .Release.Namespace }}/sa/waf-service*"
        ]
    to:
    - operation:
        ports: ["8080"]
{{- end }}
